name: head-tests

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make install
      - run: make install-dev
      - run: make test
      # - name: Test & publish code coverage
      #   # Publish code coverage on Code Climate
      #   # https://github.com/paambaati/codeclimate-action
      #   uses: paambaati/codeclimate-action@v5.0.0
      #   # Add Code Climate secret key
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ 0b1688fbcf7d8f5dddf611867bba1c29ffc4414464ea409274f87f43efaaabe1 }}
      #   with:
      #     coverageCommand: make test-coverage
      #     debug: true